In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist
mnist

<module 'tensorflow.keras.datasets.mnist' from 'C:\\Users\\acorn-509\\anaconda3\\lib\\site-packages\\tensorflow\\keras\\datasets\\mnist\\__init__.py'>

In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [4]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_train, x_test = x_train/255.0, x_test/255.0

In [7]:
# sgb = xgboostClassifier()
model = tf.keras.models.Sequential([
    # 입력 레이어
    tf.keras.layers.Flatten(input_shape=(28,28)),
    
    # 히든 레이어.. -> 노드 수 , activation function
    tf.keras.layers.Dense(128, activation = "relu"),
    
    # overfitting을 피하기 위해서 인위적으로 node를 제거하면서 연결 줄이기!!!
    # dropout
    tf.keras.layers.Dropout(0.2),
    
    # 출력레이어 --> 분류(10가지) --> 노드 수 10개, acti -> 단순 종류에 대한
    # 확률값으로 편히 보기 위해서 softmax (학습용이 아님!!!)
    tf.keras.layers.Dense(10, activation = "softmax")
])

In [8]:
model.compile(
    # 모델의 파라미터를 최적화 하는 방법 : GD, SGD, etc....
    optimizer = "adam",
    # cost function : mse, mas etc....
    loss = "sparse_categorical_crossentropy",
    # 평가기준..
    metrics = ["accuracy"]
)

In [9]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2953 - accuracy: 0.9134
Epoch 2/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1430 - accuracy: 0.9575
Epoch 3/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1057 - accuracy: 0.9683
Epoch 4/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0871 - accuracy: 0.9734
Epoch 5/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0743 - accuracy: 0.9763
Epoch 6/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0646 - accuracy: 0.9795
Epoch 7/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0589 - accuracy: 0.9817
Epoch 8/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0520 - accuracy: 0.9831
Epoch 9/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0479 - accuracy: 0.9848
Epoch 10/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.043

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.save("test.h5") # 모델 구조, 파라미터 ...

In [12]:
model_new = tf.keras.models.load_model("test.h5")
model_new.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [13]:
x_test.shape

(10000, 28, 28)

In [14]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 849us/step - loss: 0.0685 - accuracy: 0.9804


[0.06851916760206223, 0.980400025844574]

In [15]:
sum(model.predict(x_test)[0])

1.0000000566839615

In [16]:
len(model.predict(x_test)[0])

10

In [17]:
model.predict(x_test)

array([[1.7555617e-08, 1.2319820e-09, 8.1470637e-07, ..., 9.9997628e-01,
        4.9609827e-07, 1.4447565e-06],
       [9.7898191e-12, 9.6631865e-08, 9.9999988e-01, ..., 1.2538279e-20,
        2.2520632e-09, 1.4463106e-20],
       [1.4464659e-08, 9.9975783e-01, 3.6192287e-05, ..., 1.3091831e-04,
        4.0654922e-05, 5.4271993e-08],
       ...,
       [5.6710653e-13, 3.6094681e-13, 1.0786610e-13, ..., 6.3498909e-08,
        3.0348620e-08, 1.8834139e-07],
       [1.4692313e-12, 5.5011304e-14, 9.1068608e-17, ..., 2.3171018e-12,
        1.2544510e-05, 1.6225348e-13],
       [8.0759740e-08, 1.3530791e-16, 9.1613854e-09, ..., 1.5691765e-13,
        6.7887096e-10, 3.5473926e-14]], dtype=float32)

In [18]:
import numpy as np

In [19]:
np.argmax(model.predict(x_test),axis=-1)

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [20]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [21]:
x = 1
y = 0
w = tf.random.normal([1],0.1)
output = sigmoid(x * w)
print(output)

0.8634820067228999


In [23]:
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x*0.8*error
    if i % 100 == 99 : 
        print(i,"번째-Error : ", error, "// model output : ", output)

99 번째-Error :  -0.013174578153200153 // model output :  0.013174578153200153
199 번째-Error :  -0.006432221463294422 // model output :  0.006432221463294422
299 번째-Error :  -0.004251394365783512 // model output :  0.004251394365783512
399 번째-Error :  -0.003174191253075225 // model output :  0.003174191253075225
499 번째-Error :  -0.002532258859748119 // model output :  0.002532258859748119
599 번째-Error :  -0.0021061812220827757 // model output :  0.0021061812220827757
699 번째-Error :  -0.001802779371138959 // model output :  0.001802779371138959
799 번째-Error :  -0.0015757521353062685 // model output :  0.0015757521353062685
899 번째-Error :  -0.0013994889855268914 // model output :  0.0013994889855268914
999 번째-Error :  -0.001258678952845353 // model output :  0.001258678952845353


In [27]:
x = 0 
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)
for i in range(1000):
    output = sigmoid(x+w+1*b)
    error = y - output
    w = w+x*0.1*error
    b = b+1*0.1*error
    
    if i%100==99:
        print(i,"번째-Error : ",error, "// model output : ", output)

99 번째-Error :  0.08423164226383151 // model output :  0.9157683577361685
199 번째-Error :  0.046997081966557386 // model output :  0.9530029180334426
299 번째-Error :  0.03235405686688242 // model output :  0.9676459431331176
399 번째-Error :  0.024606300462624908 // model output :  0.9753936995373751
499 번째-Error :  0.019829448232515756 // model output :  0.9801705517674842
599 번째-Error :  0.016595418983267884 // model output :  0.9834045810167321
699 번째-Error :  0.014263015921278543 // model output :  0.9857369840787215
799 번째-Error :  0.012502415255072008 // model output :  0.987497584744928
899 번째-Error :  0.011126885930396568 // model output :  0.9888731140696034
999 번째-Error :  0.010022858770221243 // model output :  0.9899771412297788


In [28]:
x = np.array([
    [1,1],
    [1,0],
    [0,1],
    [0,0]
])

y = np.array([
    [0],[1],[1],[0]
])




In [29]:
x.shape

(4, 2)

In [30]:
y.shape

(4, 1)

In [32]:
model_xor = tf.keras.Sequential(
[
    tf.keras.layers.Dense(units=2,activation="sigmoid",input_shape=(2,)),
    tf.keras.layers.Dense(units=1,activation="sigmoid")
]
)

In [33]:
model_xor.compile(
    optimizer=tf.keras.optimizers.SGD(lr=0.3),
    loss="mse"
)
model_xor.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [40]:
xor_history = model_xor.fit(x,y,epochs=1000,batch_size=1)

Epoch 1/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0029
Epoch 2/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0029
Epoch 3/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0029
Epoch 4/1000
4/4 [==============================] - 0s 489us/step - loss: 0.0029
Epoch 5/1000
4/4 [==============================] - 0s 731us/step - loss: 0.0029
Epoch 6/1000
4/4 [==============================] - 0s 733us/step - loss: 0.0029
Epoch 7/1000
4/4 [==============================] - 0s 744us/step - loss: 0.0029
Epoch 8/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0028
Epoch 9/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0028
Epoch 10/1000
4/4 [==============================] - 0s 732us/step - loss: 0.0028
Epoch 11/1000
4/4 [==============================] - 0s 724us/step - loss: 0.0028
Epoch 12/1000
4/4 [==============================] - 0s 754us/step - loss: 0.0028
Epoch 13/1000
4/4 [======

4/4 [==============================] - 0s 499us/step - loss: 0.0026
Epoch 102/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0026
Epoch 103/1000
4/4 [==============================] - 0s 739us/step - loss: 0.0026
Epoch 104/1000
4/4 [==============================] - 0s 885us/step - loss: 0.0026
Epoch 105/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0025
Epoch 106/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0025
Epoch 107/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0025
Epoch 108/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0025
Epoch 109/1000
4/4 [==============================] - 0s 656us/step - loss: 0.0025
Epoch 110/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0025
Epoch 111/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0025
Epoch 112/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0025
Epoch 113/1000
4/4 

4/4 [==============================] - 0s 755us/step - loss: 0.0023
Epoch 200/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0023
Epoch 201/1000
4/4 [==============================] - 0s 757us/step - loss: 0.0023
Epoch 202/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0023
Epoch 203/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0023
Epoch 204/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0023
Epoch 205/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0023
Epoch 206/1000
4/4 [==============================] - 0s 763us/step - loss: 0.0023
Epoch 207/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0023
Epoch 208/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0023
Epoch 209/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0023
Epoch 210/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0023
Epoch 211/1000
4/4 

4/4 [==============================] - 0s 748us/step - loss: 0.0021
Epoch 298/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0021
Epoch 299/1000
4/4 [==============================] - 0s 733us/step - loss: 0.0021
Epoch 300/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0021
Epoch 301/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0021
Epoch 302/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0021
Epoch 303/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0021
Epoch 304/1000
4/4 [==============================] - 0s 639us/step - loss: 0.0021
Epoch 305/1000
4/4 [==============================] - 0s 504us/step - loss: 0.0021
Epoch 306/1000
4/4 [==============================] - 0s 799us/step - loss: 0.0021
Epoch 307/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0021
Epoch 308/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0021
Epoch 309/1000
4/4 

4/4 [==============================] - 0s 499us/step - loss: 0.0019
Epoch 396/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0019
Epoch 397/1000
4/4 [==============================] - 0s 675us/step - loss: 0.0019
Epoch 398/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0019
Epoch 399/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0019
Epoch 400/1000
4/4 [==============================] - 0s 765us/step - loss: 0.0019
Epoch 401/1000
4/4 [==============================] - 0s 650us/step - loss: 0.0019
Epoch 402/1000
4/4 [==============================] - 0s 761us/step - loss: 0.0019
Epoch 403/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0019
Epoch 404/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0019
Epoch 405/1000
4/4 [==============================] - 0s 727us/step - loss: 0.0019
Epoch 406/1000
4/4 [==============================] - 0s 741us/step - loss: 0.0019
Epoch 407/1000
4/4 

4/4 [==============================] - 0s 681us/step - loss: 0.0018
Epoch 494/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0018
Epoch 495/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0018
Epoch 496/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0018
Epoch 497/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0018
Epoch 498/1000
4/4 [==============================] - 0s 734us/step - loss: 0.0018
Epoch 499/1000
4/4 [==============================] - 0s 488us/step - loss: 0.0018
Epoch 500/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0018
Epoch 501/1000
4/4 [==============================] - 0s 510us/step - loss: 0.0018
Epoch 502/1000
4/4 [==============================] - 0s 514us/step - loss: 0.0018
Epoch 503/1000
4/4 [==============================] - 0s 685us/step - loss: 0.0018
Epoch 504/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0018
Epoch 505/1000
4/4 

4/4 [==============================] - 0s 762us/step - loss: 0.0017
Epoch 592/1000
4/4 [==============================] - 0s 734us/step - loss: 0.0017
Epoch 593/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0017
Epoch 594/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0017
Epoch 595/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0017
Epoch 596/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0016
Epoch 597/1000
4/4 [==============================] - 0s 517us/step - loss: 0.0016
Epoch 598/1000
4/4 [==============================] - 0s 761us/step - loss: 0.0016
Epoch 599/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0016
Epoch 600/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0016
Epoch 601/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0016
Epoch 602/1000
4/4 [==============================] - 0s 765us/step - loss: 0.0016
Epoch 603/1000
4/4 

4/4 [==============================] - 0s 499us/step - loss: 0.0015
Epoch 690/1000
4/4 [==============================] - 0s 491us/step - loss: 0.0015
Epoch 691/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0015
Epoch 692/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0015
Epoch 693/1000
4/4 [==============================] - 0s 491us/step - loss: 0.0015
Epoch 694/1000
4/4 [==============================] - 0s 466us/step - loss: 0.0015
Epoch 695/1000
4/4 [==============================] - 0s 732us/step - loss: 0.0015
Epoch 696/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0015
Epoch 697/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0015
Epoch 698/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0015
Epoch 699/1000
4/4 [==============================] - 0s 502us/step - loss: 0.0015
Epoch 700/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0015
Epoch 701/1000
4/4 

4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 788/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 789/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 790/1000
4/4 [==============================] - 0s 515us/step - loss: 0.0014
Epoch 791/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 792/1000
4/4 [==============================] - 0s 733us/step - loss: 0.0014
Epoch 793/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 794/1000
4/4 [==============================] - 0s 723us/step - loss: 0.0014
Epoch 795/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 796/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 797/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 798/1000
4/4 [==============================] - 0s 478us/step - loss: 0.0014
Epoch 799/1000
4/4 

4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 886/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 887/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 888/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 889/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 890/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 891/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 892/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 893/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 894/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0014
Epoch 895/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0014
Epoch 896/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0014
Epoch 897/1000
4/4 

4/4 [==============================] - 0s 499us/step - loss: 0.0013
Epoch 984/1000
4/4 [==============================] - 0s 496us/step - loss: 0.0013
Epoch 985/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0013
Epoch 986/1000
4/4 [==============================] - 0s 736us/step - loss: 0.0013
Epoch 987/1000
4/4 [==============================] - 0s 733us/step - loss: 0.0013
Epoch 988/1000
4/4 [==============================] - 0s 483us/step - loss: 0.0013
Epoch 989/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0013
Epoch 990/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0013
Epoch 991/1000
4/4 [==============================] - 0s 483us/step - loss: 0.0013
Epoch 992/1000
4/4 [==============================] - 0s 482us/step - loss: 0.0013
Epoch 993/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0013
Epoch 994/1000
4/4 [==============================] - 0s 745us/step - loss: 0.0013
Epoch 995/1000
4/4 

In [41]:
model_xor(x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.03148812],
       [0.9674782 ],
       [0.9583676 ],
       [0.03600262]], dtype=float32)>

In [42]:
for weight in model_xor.weights:
    print(weight)

<tf.Variable 'dense_3/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 5.255743 ,  5.9961667],
       [-5.064228 , -6.161034 ]], dtype=float32)>
<tf.Variable 'dense_3/bias:0' shape=(2,) dtype=float32, numpy=array([ 2.516291 , -3.2925942], dtype=float32)>
<tf.Variable 'dense_4/kernel:0' shape=(2, 1) dtype=float32, numpy=
array([[-7.871327],
       [ 8.059743]], dtype=float32)>
<tf.Variable 'dense_4/bias:0' shape=(1,) dtype=float32, numpy=array([3.7069042], dtype=float32)>


In [44]:
import pandas as pd

red = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=';')
white = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep=';')
print(red.head())
print(white.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5 

In [45]:
red['type'] = 0
white['type'] = 1
print(red.head(2))
print(white.head(2))

wine = pd.concat([red, white])
print(wine.describe())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   

   alcohol  quality  type  
0      9.4        5     0  
1      9.8        5     0  
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   

   free sulfur dioxide  total sulfur dioxide  density   pH  sulphates  \
0                 45.0                 170.0    1.001  3.0       0.45   
1                 14.0                 132.0    0.994  3.3       0.49   

   

In [46]:
print(wine.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6497 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
 12  type                  6497 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 710.6 KB
None


In [47]:
wine_norm = (wine - wine.min()) / (wine.max() - wine.min())
print(wine_norm.head())
print(wine_norm.describe())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.297521          0.413333     0.000000        0.019939   0.111296   
1       0.330579          0.533333     0.000000        0.030675   0.147841   
2       0.330579          0.453333     0.024096        0.026074   0.137874   
3       0.611570          0.133333     0.337349        0.019939   0.109635   
4       0.297521          0.413333     0.000000        0.019939   0.111296   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.034722              0.064516  0.206092  0.612403   0.191011   
1             0.083333              0.140553  0.186813  0.372093   0.258427   
2             0.048611              0.110599  0.190669  0.418605   0.241573   
3             0.055556              0.124424  0.209948  0.341085   0.202247   
4             0.034722              0.064516  0.206092  0.612403   0.191011   

    alcohol   quality  type  
0  0.202899  0.333333   0.

In [48]:
import numpy as np
wine_shuffle = wine_norm.sample(frac=1)
print(wine_shuffle.head())
wine_np = wine_shuffle.to_numpy()
print(wine_np[:5])

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
2844       0.347107          0.093333     0.186747        0.076687   0.066445   
4174       0.206612          0.106667     0.132530        0.173313   0.068106   
3803       0.280992          0.060000     0.204819        0.088957   0.054817   
607        0.289256          0.113333     0.174699        0.105828   0.066445   
1927       0.272727          0.113333     0.168675        0.015337   0.071429   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
2844             0.079861              0.209677  0.113553  0.294574   
4174             0.222222              0.398618  0.182765  0.263566   
3803             0.052083              0.241935  0.109312  0.209302   
607              0.128472              0.350230  0.181029  0.550388   
1927             0.156250              0.375576  0.105842  0.255814   

      sulphates   alcohol   quality  type  
2844   0.112360  0.420290  0.333333   1.0 

In [49]:
import tensorflow as tf
train_idx = int(len(wine_np) * 0.8)
train_X, train_Y = wine_np[:train_idx, :-1], wine_np[:train_idx, -1]
test_X, test_Y = wine_np[train_idx:, :-1], wine_np[train_idx:, -1]
print(train_X[0])
print(train_Y[0])
print(test_X[0])
print(test_Y[0])
train_Y = tf.keras.utils.to_categorical(train_Y, num_classes=2)
test_Y = tf.keras.utils.to_categorical(test_Y, num_classes=2)
print(train_Y[0])
print(test_Y[0])

[0.34710744 0.09333333 0.18674699 0.07668712 0.06644518 0.07986111
 0.20967742 0.11355311 0.29457364 0.11235955 0.42028986 0.33333333]
1.0
[0.25619835 0.2        0.1686747  0.11809816 0.08803987 0.07291667
 0.36866359 0.15326778 0.34108527 0.28089888 0.37681159 0.33333333]
1.0
[0. 1.]
[0. 1.]


In [50]:
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=48, activation='relu', input_shape=(12,)),
    tf.keras.layers.Dense(units=24, activation='relu'),
    tf.keras.layers.Dense(units=12, activation='relu'),
    tf.keras.layers.Dense(units=2, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.07), loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 48)                624       
_________________________________________________________________
dense_6 (Dense)              (None, 24)                1176      
_________________________________________________________________
dense_7 (Dense)              (None, 12)                300       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 26        
Total params: 2,126
Trainable params: 2,126
Non-trainable params: 0
_________________________________________________________________


In [51]:
history = model.fit(train_X, train_Y, epochs=25, batch_size=32, validation_split=0.25)

Epoch 1/25
122/122 [==============================] - 0s 3ms/step - loss: 0.1561 - accuracy: 0.9312 - val_loss: 0.0492 - val_accuracy: 0.9915
Epoch 2/25
122/122 [==============================] - 0s 1ms/step - loss: 0.0739 - accuracy: 0.9790 - val_loss: 0.0430 - val_accuracy: 0.9938
Epoch 3/25
122/122 [==============================] - 0s 1ms/step - loss: 0.0659 - accuracy: 0.9843 - val_loss: 0.0414 - val_accuracy: 0.9915
Epoch 4/25
122/122 [==============================] - 0s 1ms/step - loss: 0.0456 - accuracy: 0.9897 - val_loss: 0.0361 - val_accuracy: 0.9931
Epoch 5/25
122/122 [==============================] - 0s 1ms/step - loss: 0.0717 - accuracy: 0.9818 - val_loss: 0.0727 - val_accuracy: 0.9762
Epoch 6/25
122/122 [==============================] - 0s 1ms/step - loss: 0.0624 - accuracy: 0.9846 - val_loss: 0.0338 - val_accuracy: 0.9938
Epoch 7/25
122/122 [==============================] - 0s 1ms/step - loss: 0.0705 - accuracy: 0.9800 - val_loss: 0.0997 - val_accuracy: 0.9777
Epoch 

In [52]:
model.evaluate(test_X, test_Y)

41/41 [==============================] - 0s 778us/step - loss: 0.0334 - accuracy: 0.9969


[0.03341812267899513, 0.9969230890274048]